Repository 18F/samhsa-prototype, pull requests merged in 2019-10, with the labels that each got.

#468 Update filters.js
  src/utils/filters.js
Labels: content

#462 Report failed search queries
  src/actions/facilities.js
  src/actions/facility.js
  src/middleware/analytics.js
  src/utils/api.js
Labels: high-priority

#483 Move focus to What to Expect section when Learn more is clicked
  src/components/Home.js
Labels: enhancement

#526 Target new GA and rework event categories
  .env.production
  src/actions/facilities.js
  src/components/Input/Location.js
  src/middleware/analytics.js
  src/utils/api.js
Labels: launch prep

#498 Refactor CE name tracking
  src/middleware/analytics.js
Labels: launch prep
